services:
  rabbitmq:
    image: masstransit/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  eventstoredb:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16688:16686"
  mongo:
    image: mongo
    ports:
      - 27019:27017
  pullaroo.server:
    image: pullarooserver
    build:
      context: .
      dockerfile: backend/src/Pullaroo.Server/Dockerfile
    ports:
      - 5000:80
    environment:
      TelemetrySettings__JaegerAddress: jaeger
